#!/usr/bin/env zsh

if [ -d "$HOME/.nvm" ]; then
    export NVM_DIR=$HOME/.nvm

    if [ -d "$NVM_DIR/versions/node" ]; then
        declare -a NODE_GLOBALS=(`find $NVM_DIR/versions/node -maxdepth 3 -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)
    fi

    if [ -d "$NVM_DIR/current/bin" ]; then
        export PATH=$NVM_DIR/current/bin:$PATH
    fi

    NODE_GLOBALS+=("node")
    NODE_GLOBALS+=("nvm")

    load_nvm () {
        # Mirrors of nvm
        export NVM_NODEJS_ORG_MIRROR=https://npmmirror.com/mirrors/node
        export NODEJS_ORG_MIRROR=https://npmmirror.com/mirrors/node
        #export NVM_IOJS_ORG_MIRROR=

        # Let NVM create ~/.nvm/current as a soft link to current node version.
        NVM_SYMLINK_CURRENT=true

        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    }

    for cmd in "${NODE_GLOBALS[@]}"; do
        eval "${cmd}(){ unset -f ${NODE_GLOBALS} > /dev/null 2>&1; load_nvm; ${cmd} \$@ }"
    done

fi

