#!/usr/bin/env zsh

# If you are using Max OS, the "sed" command is different with GNU's "sed".
# You can execute:
# brew install gnu-sed
# to install GNU sed.

if [ -d "/usr/local/Cellar/gnu-sed/" ]; then
    alias sed="gsed"
fi
