#!/usr/bin/env zsh

# Scripts in $IDLEBOX/scripts/ .
# For same name scripts, private scripts have higher priority.
export PATH=$PATH:$IDLEBOX/scripts/private
export PATH=$PATH:$IDLEBOX/scripts/public
