#!/usr/bin/env zsh

# Git push with tags
alias gpwt="git push --tags && git push"

# Git push with same branch name. Require $IDLEBOX/scripts/public/git-push-to-same-branch.
alias gpsb="git-push-to-same-branch"

