#!/usr/bin/env zsh

shell-reload(){
  # Source all scripts in zshrcs/
  # For same name scripts, private scripts have higher priority.
  PRIVATE_SCRIPT_NAMES=($(cd $IDLEBOX_ZSHRCS_PATH/private/ && find . -maxdepth 1 -type f))
  PUBLIC_SCRIPT_NAMES=($(cd $IDLEBOX_ZSHRCS_PATH/public/ && find . -maxdepth 1 -type f))
  for public_script_name in $PUBLIC_SCRIPT_NAMES; do
    do_load_private_script=false
    for private_script_name in $PRIVATE_SCRIPT_NAMES; do
      if [[ $public_script_name == $private_script_name ]]; then
        do_load_private_scrip=true
        break
      fi
    done
    if [[ $do_load_private_scrip == true ]]; then
      source $IDLEBOX_ZSHRCS_PATH/private/$private_script_name
    else
      source $IDLEBOX_ZSHRCS_PATH/public/$public_script_name
    fi
  done
  unset do_load_private_script
  unset PRIVATE_SCRIPT_NAMES
  unset PUBLIC_SCRIPT_NAMES
}
