#!/usr/bin/env zsh

# Download Oh My Zsh.
git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh

# Download NVM.
git clone https://github.com/nvm-sh/nvm.git $HOME/.nvm

# Download Spaceship ZSH theme.
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# Install IdleBox.
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/libook/IdleBox/master/install)"
