#!/usr/bin/env zsh

cd $HOME
git clone https://github.com/libook/IdleBox.git .idlebox
if [ ! -f '.idlebox/config' ];then
  cp .idlebox/config.example .idlebox/config
fi
if [ -f '.zshrc' ];then
  mv .zshrc .zshrc.backup
fi
ln -s $HOME/.idlebox/zshrc $HOME/.zshrc

source $HOME/.zshrc

