#!/usr/bin/env zsh

# Download Oh My Zsh.
git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh

# Download mise.
curl https://mise.run | sh

# Install IdleBox.
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/libook/IdleBox/master/install)"
