#!/usr/bin/env zsh

# This script can export all images in a docx file.
# Only works on MacOS, for now.
# Require LibreOffice and ImageMagick.
######


# Create tmp directory:
TMP_DIRECTORY="$(mktemp -d)"
echo "Use directory: $TMP_DIRECTORY"

FILE_NAME=`echo $1 |awk -F '/' '{print $NF}'|sed -e 's/\..*$//'`

# Copy file and change extension name to zip:
cp $1 $TMP_DIRECTORY/$FILE_NAME.zip

cd $TMP_DIRECTORY/

# Uncompress:
unzip ./$FILE_NAME.zip

cd ./word/media/

# Convert emf format to png:
/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to png *.emf

mkdir ../../images

# Copy images. https://support.office.com/en-us/article/graphic-file-types-you-can-insert-and-save-dad53574-3384-4ced-b472-348d37c326a7 Only support these formats for now:
find ./ -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.bmp -o -iname \*.gif \) -exec cp "{}" ../../images/ \;

find ./ -name "*.png" -exec convert {} -trim ../../images/{} \;
cd ../../images

echo 'Successful! Please check '$PWD

open .

