#!/usr/bin/env zsh

# git-clone-all "SEARCH" TARGET_DIRECTORY "OTHER_ARGUMENTS"

# Use this API https://developer.github.com/v3/search/#search-repositories
# Use the same search syntax as on the website https://help.github.com/en/articles/searching-for-repositories

URLS=`curl -s https://api.github.com/search/repositories\?q\=$1 | grep clone_url | awk -F \" '{print $4}'`

echo $URLS

echo "\n"

while true; do
    read "yn?Do you want to clone these repositories to $2 ? Input 'Yes' to do this. "
    case $yn in
        Yes* )
	    mkdir -p $2
	    cd $2
            echo $URLS | xargs -I URL git clone URL $3
            break
            ;;
        * )
            echo "Not 'Yes'. Canceled."
            exit
            ;;
    esac
done
