#!/usr/bin/env zsh

# Download latest release from GitHub.
# $1 is people_or_organization_name/project_name.
# For example: github-latest-release-download videolan/vlc

# If $1 is a GitHub url:
repo_name=$(echo "$1" | grep "github.com" | awk -F "github.com" '{print $2}' | awk -F / '{print $2"/"$3}')
if [[ -z $repo_name ]];then
  repo_name=$1
fi

# Download
if [[ ! -z $repo_name ]];then
  url_list=(`curl --silent https://api.github.com/repos/$repo_name/releases/latest | awk '/browser_download_url/ { print $2 }' | sed 's/"//g'`)
  PS3="Input number and press ENTER; or exit with Ctrl+c:"
  select url ($url_list) {
    echo $url
    curl -LOC - $url
  }
fi
