#!/usr/bin/env zsh
# Get my IP

if command -v "ifconfig" >/dev/null; then
  # Use ifconfig
  ifconfig \
  | grep "inet " \
  | awk '{print $2}'
elif command -v "ip" >/dev/null; then
  # Use ip
  ip addr show \
  | grep "inet " \
  | awk '{print $2}' \
  | awk -F "/" '{print $1}'
else
  echo "Need command 'ifconfig' or 'ip'."
fi
