#!/usr/bin/env zsh

# - Oh My Zsh
echo "Updating Oh My Zsh..."
zsh $ZSH/tools/upgrade.sh

# - Idlebox
echo "Updating Idlebox..."
update-idlebox

# - System update
echo "Updating system..."
# -- MacOS
if command -v "brew" >/dev/null; then
  brew update && brew upgrade && brew upgrade --cask --greedy
# -- Linux
# --- Arch based
elif command -v "paru" >/dev/null; then
  paru
elif command -v "yay" >/dev/null; then
  yay
elif command -v "pacman" >/dev/null; then
  sudo pacman -Syu
# --- Termux
elif command -v "pkg" >/dev/null; then
  pkg update && pkg upgrade
# --- Debian based
elif command -v "apt" >/dev/null; then
  sudo apt update && sudo apt full-upgrade
elif command -v "apt-get" >/dev/null; then
  sudo apt-get update && sudo apt-get dist-upgrade
# --- Red Hat based
elif command -v "dnf" >/dev/null; then
  sudo dnf update
elif command -v "yum" >/dev/null; then
  sudo yum update
fi

# - mise
if command -v "mise"; then
  echo "Updating mise..."
  mise self-update
  echo "Updating mise tools..."
  mise upgrade
fi

echo "Complete!"
